### ISSUE TITLE
O site está com erros de ssl

### ISSUE THREAD

**Issue by willsoares** [gabrielferreiraa/gerador-de-tweet-do-bolsonaro#12]
O site se encontra inacessível devido à erros no ssl. 

Repro steps:

1. Acessar o [site](http://gerador-de-tweet-do-bolsonaro.netlify.com/)
2. Ver o erro gerado `SEC_ERROR_REVOKED_CERTIFICATE `

**Comment by gabrielferreiraa** [comment]
Boa tarde @willsoares aqui está tudo normal, tanto com o site como com `https`! Consegue verificar se ai continua com erro?

**Comment by willsoares** [comment]
Acabei de ver aqui, tá certo de novo.

Que estranho cara
