### ISSUE TITLE
retweets, curtidas e imagens aleatórias

### ISSUE THREAD

**Issue by LucasNaja** [gabrielferreiraa/gerador-de-tweet-do-bolsonaro#2]
Seria uma boa colocarem pra gerar os retweets/curtidas...

E ainda melhor, imagens aleatórias: https://thispersondoesnotexist.com/

**Comment by gabrielferreiraa** [comment]
Que show @LucasNaja! 

Acho bem válido, ficaria realmente mais interessante. Se possível abre um PR, seria bem legal :D

**Comment by gabrielferreiraa** [comment]
@LucasNaja vou fechar a issue e aguardo a abertura do seu PR para essa implementação :D Abraço!
