### ISSUE TITLE
Responsividade no mobile

### ISSUE THREAD

**Issue by christyanbrayan** [gabrielferreiraa/gerador-de-tweet-do-bolsonaro#24]
Quando na vertical o layout fica quebrado, sem funcionar o zoom pra diminuir e ter uma visão total do quadro de tweet. A ação de editar a mensagem está funcional, mas prejudicada pela visão.
Já na horizontal a visão fica ok, talvez com demasiado zoom.

Apesar de envolver tecnologias que ainda sou iniciante, gostaria de contribuir com um PR nesse sentido, se aceitar, apesar de talvez demorar um pouco. Acho que seria interessante por conta de muitos descobrirem e acessarem a aplicação no mobile, e talvez se distanciem ao visualizarem da forma como está.

[horizontal](https://imgur.com/a/cijgwHW)
[vertical](https://imgur.com/a/GYFdTB7)

**Comment by gabrielferreiraa** [comment]
Não fizemos o mobile, de fato! Pode abrir o PR. Será muito bem-vindo 😄
