### ISSUE TITLE
[Sugestão] deletar | mudar o projeto?

### ISSUE THREAD

**Issue by mauriciosoares** [gabrielferreiraa/gerador-de-tweet-do-bolsonaro#3]
Antes de mais nada, eu não sou de direita, e não compactuo com as idéias políticas do nosso atual presidente, mas acho justo levantar essa questão aqui...

Um dos motivos do Bolsonaro ter se tornado presidente da república, foi a grande quantidade de fake news que foi espalhada, e na minha opinião não é muito ético criar um aplicativo que facilite ainda mais esse processo.

Novamente, não estou querendo defender a integridade do Bolsonaro, mas o que eu vejo acontecendo é essa ferramenta se tornar popular (até pq a UI esta super bem feita, parabéns 😄), e a galera começar a criar tweets fakes aos montes.

O que pode acontecer é a galera que apóia o Bolsonaro cair matando sobre a integridade da galera que é contra o Bolsonaro, e acabar apoiando mais esse kra, e sinceramente, espero que nas próximas eleições ele não seja re-eleito.

Outro bom motivo para deletar ou mudar o projeto seriam questões legais mesmo, eu não sou advogado, muito menos tenho conhecimento técnico para afirmar que vc possa ter problemas, mas seu aplicativo foi criado intencionalmente para difamar o Bolsonaro, se o app acabar se popularizando, e saindo em algum veiculo de mídia popular, eu não dúvido nada vc receber uma ligaçãozinha de algum advogado querendo te ferrar.

Pela terceira vez, não quero defender o kra, mas acho relevante levantar esses pontos.

Se mesmo assim vc não tiver interesse em deletar o projeto (vc esta no seu direito, e não vou te importunar por isso), eu gostaria de dar uma sugestão: colocar uma marca d'agua na imagem, com um textinho `Esse tweet foi gerado com o "xyz" (link do site), e não é necessariamente verdadeiro`, isso vai acabar atraindo uma galera para seu app, e será facil de reconhecer que a notícia pode ser falsa.

É isso ai, @gabrielferreiraa não quero desmerecer seu projeto, o código esta muito maneiro, e da para ver que como programador vc é manda muito bem, mas tenta levar em consideração esse meu ponto de vista, e tome a decisão que vc achar melhor 🕺 

Abs!

**Comment by gabrielferreiraa** [comment]
Fala @mauriciosoares, beleza?

Primeiramente, você tem razão em 100% do que disse!
Eu também não sou advogado e não tenho conhecimento técnico pra saber se isso trará algum problema (acho que não).

Não gostaria de deletar o projeto, porém gostei bastante da sua ideia de colocar esse texto, sendo marca d'agua ou de outra forma para reconhecer que é um tweet falso. Acho bastante válido!

Vou avaliar o mais rápido possível isso!

Obrigado pela alerta e pelos elogios! Você foi incrível.

Abraço!

**Comment by gabrielferreiraa** [comment]
Boa noite @mauriciosoares, tranquilo?
Como foi uma ideia sua, nada mais justo que pedir sua opinião. Feedbacks são bem vindos xD

![tweet (4)](https://user-images.githubusercontent.com/17201177/54164276-cbd47080-443a-11e9-99cf-b31d24c969fe.png)

**Comment by mauriciosoares** [comment]
Esta foda! Por mim vai que vai ❤️ 

Vou até fechar a issue aqui 🕺
