### ISSUE TITLE
Possibilidade de alterar as thumbs de pessoas que curtiram

### ISSUE THREAD

**Issue by micas06gua** [gabrielferreiraa/gerador-de-tweet-do-bolsonaro#8]
Já imaginou, eu poder colocar uma thumb diferenciada para cada seguidor? seria legal... 

Eu digo isso, atribuindo um Json com todas as thumbs de avatar.

**Comment by vicainelli** [comment]
@micas06gua tem uma issue pra isso ae, da uma olhada #2

**Comment by brunooomelo** [comment]
Fiz a implementação das thumb, mas tive problema na hora de exportar para .png.
quando aliviar o tempo aqui, vou rever a PR.

**Comment by gabrielferreiraa** [comment]
Atualmente temos um problema para exportação de imagem em CDN. @brunooomelo precisamos resolver esse problema naquela sua PR se possível. Qualquer coisa pode entrar em contato comigo!

Vou fechar a issue por já termos um PR com essa ideia, valeu @micas06gua !
